version: "3.5"
services:
  docker-mysql:
     image: mysql:5.7
     container_name: db-mysql
     environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_DATABASE=notes_app
        - MYSQL_USER=webmail
        - MYSQL_PASSWORD=webmail
     ports:
      - 3306:3306  
   
   
   
  
   