version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Janna@05
       MYSQL_DATABASE: notes_app
       MYSQL_USER: root	
       MYSQL_PASSWORD: admin

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8085:8085"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: admin
       WORDPRESS_DB_PASSWORD: admin
volumes:
    db_data: