trigger:
- develop

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'spring-boot-mysql-rest-api'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
