version: "3"
services: 
  db:
    image: mysql:5.7
    container_name: db-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: notes_app
      MYSQL_USER: webmail
      MYSQL_PASSWORD: webmail
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - "db_data:/var/lib/mysql"
  spring-boot-mysql-rest-api: 
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on: 
      - db
    environment: 
          - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/notes_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false 
          - SPRING_DATASOURCE_USERNAME=webmail 
          - SPRING_DATASOURCE_PASSWORD=webmail
    image: "ahmedelshfie/spring-boot-mysql-rest-api:1.0.0"
    container_name: spring-api
    ports: 
      - "8085:8085"
    restart: always
    volumes: 
      - /data/springboot-docker-compose-app
volumes: 
  db_data: ~